apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: feature-flag
spec:
  releaseName: feature-flag
  chart:
    spec:
      chart: unleash
      sourceRef:
        kind: HelmRepository
        name: unleash
        namespace: flux-system
      version: "3.0.4"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: feature-flag-values