apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops
spec:
  releaseName: sops
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops
        namespace: flux-system
      version: "0.17.2"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sops-values