
name: e2e

on:
  push:
    branches: [main]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.4.0
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
        with:
          version: 0.27.4
      - name: Install Flux in Kubernetes 
        run: flux install --log-level debug
      - name: Create Secret Git Plateform
        run: |
          kubectl apply -f - <<EOF > cat 
          apiVersion: v1
          kind: Secret
          metadata:
            name: flux-system
            namespace: flux-system
          type: Opaque
          data:
            username: TW91YWRvdWFraWw=
            password: Z2hwX1N4Y1NhVUNFSTJsZ0E5c053R3pieEFBNGNQVU1ySTBjdjdhcA==
      - name: create GitRepository
        run: |
          kubectl apply -f - <<EOF > cat
          apiVersion: source.toolkit.fluxcd.io/v1beta1
          kind: GitRepository
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            interval: 1m
            ref:
              branch: main
            secretRef:
              name: flux-system
            url: https://github.com/Mouadouakil/gots.git
          EOF
          flux reconcile source git flux-system
          flux create kustomization flux-system \
          --interval=1m \
          --source=flux-system \
          --path=./clusters/nemox
      - name: wait for deployment
        run: |
          sleep 3m
      - name: List reconciliations
        run: |
          flux get all --all-namespaces
      - name: List Deployments
        run: |
          kubectl get deployments --all-namespaces
      - name: List Kustomizations
        run: |
          sleep 1m
          flux get kustomization
